/* eslint-disable quotes */
export const LANG = {
  ru: {
    login: 'Войти',
    logout: 'Выйти',
    settings: 'Настройки',
    dark: 'Темная',
    light: 'Светлая',
    ru: 'Рус',
    en: 'Англ',
    specialFor: 'Специально для ',
    rsSchool: 'РсСкул',
    footer: {
      irinaiid: 'иринаиид',
      predmaxim: 'предмаксим',
      sanich123: 'санич123',
    },
    graphiql: 'GRAPHiQl',
    main: {
      h1: 'Песочница GraphiQL',
      p: 'Это песочница/IDE для создания графикюл запросов',
      startBtn: 'Давай начнем!',
    },
    tabs: ['Запросы к любой API', 'Подсветка синтаксиса', 'Документация', 'Схема', 'Переменные запросов'],
    graphQlPage: {
      queryHeader: 'Запросы',
      variablesHeader: 'Переменные',
      docsHeader: 'Доки',
      schemaHeader: 'Схема',
    },
  },
  en: {
    login: 'Sign-in',
    logout: 'Sign-out',
    settings: 'Settings',
    dark: 'Dark',
    light: 'Light',
    ru: 'Ru',
    en: 'En',
    specialFor: 'Special for ',
    rsSchool: 'RsSchool',
    footer: {
      irinaiid: 'irinaiid',
      predmaxim: 'predmaxim',
      sanich123: 'sanich123',
    },
    graphiql: 'GRAPHiQl',
    main: {
      h1: 'GraphiQL Playground',
      p: `It is a playground/IDE for graphQL requests`,
      startBtn: 'Get Started!',
    },
    tabs: ['Requests to any API', 'Syntax highlighting', 'Documentation', 'Schema', 'Query variables'],
    graphQlPage: {
      queryHeader: 'Queries',
      variablesHeader: 'Variables',
      docsHeader: 'Docs',
      schemaHeader: 'Schema',
    },
  },
};
