export const LANG = {
  ru: {
    login: 'Войти',
    logout: 'Выйти',
    settings: 'Настройки',
    dark: 'Темная',
    light: 'Светлая',
    ru: 'Рус',
    en: 'Англ',
    specialFor: 'Специально для',
    rsSchool: 'РсСкул',
    footer: {
      irinaiid: 'иринаиид',
      predmaxim: 'предмаксим',
      sanich123: 'санич123',
    },
    graphiql: 'ГРАФиКюЛ',
  },
  en: {
    login: 'Sign-in',
    logout: 'Sign-out',
    settings: 'Settings',
    dark: 'Dark',
    light: 'Light',
    ru: 'Ru',
    en: 'En',
    specialFor: 'Special for',
    rsSchool: 'RsSchool',
    footer: {
      irinaiid: 'irinaiid',
      predmaxim: 'predmaxim',
      sanich123: 'sanich123',
    },
    graphiql: 'GRAPHiQl',
  },
};
